---
- name: Ensure that the tor and torsocks packages are installed
  tags: tor
  become: true
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: tor_yum
  with_items:
    - tor
    - torsocks

- block:
  - name: Applying torrc and torsocks configurations
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      owner: root
      group: root
      mode: 0644
    notify: restart tor
    with_items:
      - { src: torrc.j2, dst: /etc/tor/torrc }
      - { src: torsocks.conf.j2, dst: /etc/tor/torsocks.conf }

  - name: Enable and start the tor service on boot
    service:
      enabled: yes
      name: tor
      state: started
  tags: tor
  become: true
  when: tor_yum|success
...
