---
- name: Attempting to execute os family specific tasks (Debian)
  tags: tor
  include_tasks: "tor_{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'Debian'

- name: Attempting to execute os family specific tasks (RedHat)
  tags: tor
  include_tasks: "tor_{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Applying torrc and torsocks configurations
  tags: tor
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  notify: restart tor
  with_items:
    - { src: torrc.j2, dst: /etc/tor/torrc }
    - { src: torsocks.conf.j2, dst: /etc/tor/torsocks.conf }
  when: tor_package is success

- name: Attempting to create tor hidden services directories, if applicable
  tags: tor
  become: true
  no_log: true
  file:
    path: "/var/lib/tor/{{ item.dir }}"
    owner: "{{ tor_owner }}"
    group: "{{ tor_group }}"
    mode: 0700
    state: directory
  with_items: "{{ torrc_hiddenservices }}"
  when:
    - item.dir is defined
    - tor_package is success

- name: Attempting to overlay hidden services private keys, if applicable
  tags: tor
  become: true
  no_log: true
  template:
    src: torrc_hiddenservices.j2
    dest: "/var/lib/tor/{{ item.dir }}/private_key"
    owner: "{{ tor_owner }}"
    group: "{{ tor_group }}"
    mode: 0600
  notify: restart tor
  with_items: "{{ torrc_hiddenservices }}"
  when:
    - item.dir is defined
    - item.private_key is defined
    - tor_package is success

- name: Ensure that tor is started and enabled on boot
  tags: tor
  become: true
  service:
    enabled: yes
    name: tor
    state: started
  when: tor_package is success
...
