---
- name: Ensure that the tor and torsocks packages are installed
  tags: tor
  become: true
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: tor_yum
  with_items:
    - tor
    - torsocks

- name: Applying torrc and torsocks configurations
  tags: tor
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  notify: restart tor
  with_items:
    - { src: torrc.j2, dst: /etc/tor/torrc }
    - { src: torsocks.conf.j2, dst: /etc/tor/torsocks.conf }
  when: tor_yum is success

- name: Attempting to create tor hidden services directories, if applicable
  tags: tor
  become: true
  no_log: true
  file:
    path: "/var/lib/tor/{{ item.dir }}"
    owner: toranon
    group: toranon
    mode: 0700
    state: directory
  with_items: "{{ torrc_hiddenservices }}"
  when:
    - item.dir is defined
    - tor_yum is success

- name: Attempting to overlay hidden services private keys, if applicable
  tags: tor
  become: true
  no_log: true
  template:
    src: torrc_hiddenservices.j2
    dest: "/var/lib/tor/{{ item.dir }}/private_key"
    owner: toranon
    group: toranon
    mode: 0600
  notify: restart tor
  with_items: "{{ torrc_hiddenservices }}"
  when:
    - item.dir is defined
    - item.private_key is defined
    - tor_yum is success

- name: Ensure that tor is started and enabled on boot
  tags: tor
  become: true
  service:
    enabled: yes
    name: tor
    state: started
  when: tor_yum is success
...
