---
- name: Ensure that the tor and torsocks packages are installed
  tags: tor
  become: true
  yum:
    enablerepo: epel
    name: "{{ item }}"
    state: present
  register: tor_yum
  with_items:
    - tor
    - torsocks

- block:
  - name: Applying torrc and torsocks configurations
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      owner: root
      group: root
      mode: 0644
    notify: restart tor
    with_items:
      - { src: torrc.j2, dst: /etc/tor/torrc }
      - { src: torsocks.conf.j2, dst: /etc/tor/torsocks.conf }

  - name: Creating tor hidden services directories (if applicable)
    no_log: true
    file:
      path: "/var/lib/tor/{{ item.dir }}"
      owner: toranon
      group: toranon
      mode: 0700
      state: directory
    with_items: "{{ torrc_hiddenservices }}"
    when: item.dir is defined

  - name: Applying tor hidden services private keys (if applicable)
    no_log: true
    template:
      src: torrc_hiddenservices.j2
      dest: "/var/lib/tor/{{ item.dir }}/private_key"
      owner: toranon
      group: toranon
      mode: 0600
    notify: restart tor
    with_items: "{{ torrc_hiddenservices }}"
    when:
      - item.dir is defined
      - item.private_key is defined

  - name: Enable and start the tor service on boot
    service:
      enabled: yes
      name: tor
      state: started
  tags: tor
  become: true
  when: tor_yum|success
...
