---
- name: Attempting to set os family specific facts (Debian)
  tags: tor
  set_fact:
    tor_group: debian-tor
    tor_owner: debian-tor

- name: Ensure that the tor and torsocks packages are installed (Debian)
  tags: tor
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: tor_package
  with_items:
    - tor
    - torsocks
...
